### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by fukemy** [growse/asterisk-docker#31]
Hi there, thanks you for working hard on Docker + Asterisk. I am trying to research everywhere to finding my solution about SIP trunk and Pjsip Register. Can you help me to know about this:

 My question is:
  1. If I run with `--net=host`, I can make my SIP trunk connected, but my `pjsip endpoints` can not be registered
  2. If I run with expose port only: `-p 5060:5060/udp ....`, I can register my `pjsip endpoints` but the trunk is UNREACHABLE.

**Comment by growse** [comment]
Hey - apologies, I'm not really able to help troubleshoot your setup. I'd start with tcpdump / wireshark to see the packets flowing and figure out what's failing there.
